name: MacOS
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        qt_ver: [5.9.9,5.12.10,5.15.2]
        qt_arch: [clang_64]
    env:
      targetName: TaoQuickApp
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.10.0
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          # submodules: 'true'
      - name: build macos
        run: |
          qmake
          make