name: Ubuntu
# Qt官方没有linux平台的x86包
on: 
  push:
    paths:
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,ubuntu-20.04]
        qt_ver: [5.9.9,5.12.10,5.15.2]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          # submodules: 'true'
      - name: build ubuntu
        run: |
          qmake
          make